import { Theme } from "../theme.slint";
import { ToolButton } from "button.slint";
export component SegmentedControl inherits HorizontalLayout {
    in property <[string]> model;
    in-out property <int> current-index;
    in property <bool> enabled:true;
    callback selected(int);
    height:Theme.control-regular;spacing:Theme.gap-small;
    for label[index] in root.model: ToolButton {has-icon:false;text:label;enabled:root.enabled;active:root.current-index==index;horizontal-stretch:1;clicked=>{root.current-index=index;root.selected(index);}}
}
