"""Vendor zui's `gpui_macos` with SubTake's patches on top.

SubTake renders on zeronsh/zui at the rev pinned in Cargo.toml. The one
crate it changes, `gpui_macos` (the Metal renderer and its shaders), is
copied from that rev into `vendor/gpui_macos`, `patches/gpui_macos/*.patch`
are applied, and Cargo.toml's `[patch]` points the build at it; every other
zui crate still comes from zui.

Run it after changing the zui rev:

    python3 scripts/vendor-gpui.py

The crate's manifest inherits from zui's workspace, which is not ours, so
it is rewritten standalone from `cargo metadata`: its zui path dependencies
become git dependencies at the same rev, so they are the crates the rest of
the build uses. The rev copied is written to `vendor/gpui_macos/ZUI_REV`,
and `scripts/check-ui-primitives.py` fails while it differs from Cargo.toml's.
A patch that no longer applies stops the script; fix it against the new rev.
"""
from pathlib import Path
import json
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
URL = "https://github.com/zeronsh/zui"
CRATE = "gpui_macos"
VENDOR = ROOT / "vendor" / CRATE
PATCHES = ROOT / "patches" / CRATE
# What the build needs: the crate's tests and their harness are zui's.
KEEP = ("src", "build.rs", "LICENSE-APACHE")


def pinned_rev(root=ROOT):
    """The zui rev Cargo.toml pins `gpui` at."""
    match = re.search(r'^gpui\s*=\s*\{[^}]*rev\s*=\s*"([0-9a-f]{40})"',
                      (root / "Cargo.toml").read_text(), re.M)
    if not match:
        raise SystemExit("Cargo.toml: no zui rev pinned for gpui")
    return match.group(1)


def checkout(rev, scratch):
    """zui at `rev`: Cargo's own checkout when it has one, or a fresh clone."""
    for path in (Path.home() / ".cargo/git/checkouts").glob(f"zui-*/{rev[:7]}"):
        if (path / "crates" / CRATE).is_dir():
            return path
    path = Path(scratch) / "zui"
    subprocess.run(["git", "clone", "--quiet", "--filter=blob:none", URL, str(path)], check=True)
    subprocess.run(["git", "-C", str(path), "checkout", "--quiet", rev], check=True)
    return path


def toml(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return "[" + ", ".join(toml(v) for v in value) + "]"
    return json.dumps(value)


def dependency(dep, rev):
    """One resolved dependency as a standalone manifest entry."""
    fields = {}
    if dep.get("rename"):
        fields["package"] = dep["name"]
    source = dep.get("source") or ""
    if dep.get("path"):
        # A zui crate: the same one the build takes from zui's git.
        fields["git"] = URL
        fields["rev"] = rev
    elif source.startswith("git+"):
        git, _, query = source[4:].partition("?")
        fields["git"] = git
        key, _, value = query.partition("=")
        fields[key] = value.split("#")[0]
    if dep["req"] != "*":
        fields["version"] = dep["req"]
    if not dep["uses_default_features"]:
        fields["default-features"] = False
    if dep["features"]:
        fields["features"] = dep["features"]
    if dep["optional"]:
        fields["optional"] = True
    return "{ " + ", ".join(f"{k} = {toml(v)}" for k, v in fields.items()) + " }"


def manifest(package, rev):
    lines = [
        "# Generated by scripts/vendor-gpui.py from zeronsh/zui at " + rev + ".",
        "# Do not edit; change patches/gpui_macos and run the script.",
        "[package]",
        f"name = {toml(package['name'])}",
        f"version = {toml(package['version'])}",
        f"edition = {toml(package['edition'])}",
        f"license = {toml(package['license'])}",
        "publish = false",
        "autotests = false",
        "",
        "[lib]",
        'path = "src/gpui_macos.rs"',
        "",
        "[features]",
    ]
    lines += [f"{toml(k)} = {toml(v)}" for k, v in sorted(package["features"].items())]
    # zui's workspace allows these, raised by the objc macros it expands.
    lines += ["", "[lints.rust]", 'unexpected_cfgs = { level = "allow" }']
    sections = {}
    for dep in package["dependencies"]:
        if dep["kind"] == "dev":
            continue
        kind = "build-dependencies" if dep["kind"] == "build" else "dependencies"
        section = f"target.'{dep['target']}'.{kind}" if dep["target"] else kind
        name = dep.get("rename") or dep["name"]
        sections.setdefault(section, []).append(f"{toml(name)} = {dependency(dep, rev)}")
    for section, entries in sections.items():
        lines += ["", f"[{section}]"] + entries
    return "\n".join(lines) + "\n"


def main():
    rev = pinned_rev()
    with tempfile.TemporaryDirectory() as scratch:
        zui = checkout(rev, scratch)
        metadata = json.loads(subprocess.check_output(
            ["cargo", "metadata", "--no-deps", "--offline", "--format-version", "1"], cwd=zui))
        package = next(p for p in metadata["packages"] if p["name"] == CRATE)
        if VENDOR.exists():
            shutil.rmtree(VENDOR)
        VENDOR.mkdir(parents=True)
        for name in KEEP:
            source = zui / "crates" / CRATE / name
            (shutil.copytree if source.is_dir() else shutil.copy2)(source, VENDOR / name)
    (VENDOR / "Cargo.toml").write_text(manifest(package, rev))
    for patch in sorted(PATCHES.glob("*.patch")):
        applied = subprocess.run(
            ["git", "apply", "--directory", str(VENDOR.relative_to(ROOT)), str(patch)], cwd=ROOT)
        if applied.returncode:
            raise SystemExit(f"{patch.relative_to(ROOT)} no longer applies to zui {rev[:8]}; "
                             "fix it against the new rev and run the script again")
        print(f"applied {patch.relative_to(ROOT)}")
    (VENDOR / "ZUI_REV").write_text(rev + "\n")
    print(f"vendored {CRATE} from zui {rev[:8]} into {VENDOR.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
